### PR TITLE
Fix ranch player list showing incorrect age and not respecting privacy options

### LINKED ISSUE #120: Fix ranch player list bug
The ranch player list does not properly show gender nor does it respect privacy settings.

### PR DESCRIPTION
**Pull request by SergeantSerk**
Fixes an issue where ranch player list did not correctly show character age and gender, and did not respect hiding gender privacy option. Also changes the age and respects the privacy option on the fly with notify commands.

Character "Sushi" with hidden gender and age
image

Character "Ihsus" with age 19 (adult) and open privacy
image

Notify privacy on the fly.
image

Fixes #120

### CODE REVIEW

**Comment by SergeantSerk** [comment]
Age = 0 - implictly hides age/gender
Age = 12,13,16,19 - correctly shows age group
`protocolCharacter.profileIcon` is actually just used to display the role of the player like GM (but OP has not been found, does it exist?)

Ready to review

File: src/server/ranch/RanchDirector.cpp [hunk 1]
```diff
@@ -311,7 +311,43 @@ RanchDirector::RanchDirector(ServerInstance& serverInstance)
...
+    [this](ClientId clientId, const auto& command)
+    {
+      protocol::AcCmdCRChangeAgeCancel response;
+      _commandServer.QueueCommand<decltype(response)>(
+        clientId,
+        [response]()
+        {
+          return response;
+        });
+    });
```
Comment (rgnter) [inline src/server/ranch/RanchDirector.cpp:332]: Is this correct? Handling client-bound message and also responding with the same message?

**Review by rgnter — CHANGES_REQUESTED** [review]

File: src/server/ranch/RanchDirector.cpp (hunk 1 above)
Comment (SergeantSerk) [reply src/server/ranch/RanchDirector.cpp]: Removed the handler

**Review by rgnter — APPROVED** [review]
